version: 2.1
jobs:
  node:
    working_directory: ~/app
    docker:
      - image: cimg/node:12.16

    steps:
      - checkout:
          path: ~/app

      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run:
          name: Yarn Install For React
          command: yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules
      #Test Eslint and flow 
      - run:
          name: Eslint Test
          command: yarn run eslint


deploy_steps_aws: &deploy_steps_aws
  parameters:
    aws_access_key_id:
      type: string
    aws_secret_access_key:
      type: string
  steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true
    - aws-cli/install
    - aws-cli/configure:
        aws-access-key-id: << parameters.aws_access_key_id >>
        aws-secret-access-key: << parameters.aws_secret_access_key >>
    - *aws_login
    - attach_workspace:
        at: /tmp

workflows:
  node-android:
    jobs:
      - node
      - deploy_steps_aws:
          requires:
            - node